update=Sunday, August 26, 2018 'PMt' 03:19:19 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=/Users/kristenkeilman/Desktop/KiCad Libraries/Adafruit-Eagle-Library.kicad-master/adafruit
LibName31=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Addressable-Specialty
LibName32=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName33=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Automotive-Relays
LibName34=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Balun
LibName35=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Barrel-Audio-Connectors
LibName36=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName37=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName38=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName39=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName40=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Coaxial-Connectors-RF
LibName41=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Current-Transducers
LibName42=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_D-Sub-Connectors
LibName43=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName44=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName45=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName46=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName47=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName48=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_DC-DC-Converters
LibName49=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Digital-Isolators
LibName50=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName51=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName52=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName53=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Diodes-Zener-Single
LibName54=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LCD-OLED-Graphic
LibName55=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName56=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Embedded-Microcontrollers
LibName57=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Encoders
LibName58=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName59=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName60=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Fixed-Inductors
LibName61=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Fuses
LibName62=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Gas-Sensors
LibName63=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName64=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Image-Sensors-Camera
LibName65=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName66=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName67=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName68=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName69=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Controllers
LibName70=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName71=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-I-O-Expanders
LibName72=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Modules
LibName73=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName74=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName75=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Interface-Specialized
LibName76=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_LED-Indication-Discrete
LibName77=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName78=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName79=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName80=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Linear-Comparators
LibName81=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName82=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Flip-Flops
LibName83=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName84=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Multivibrators
LibName85=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Shift-Registers
LibName86=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName87=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName88=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName89=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName90=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName91=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName92=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Memory
LibName93=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Microphones
LibName94=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName95=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Modular-Connectors-Jacks
LibName96=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName97=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName98=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName99=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Navigation-Switches-Joystick
LibName100=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName101=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName102=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName103=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName104=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName105=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Logic-Output
LibName106=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName107=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName108=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Oscillators
LibName109=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName110=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Chargers
LibName111=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Battery-Management
LibName112=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName113=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName114=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Gate-Drivers
LibName115=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-LED-Drivers
LibName116=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName117=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName118=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName119=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName120=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName121=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Supervisors
LibName122=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Thermal-Management
LibName123=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName124=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Reference
LibName125=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName126=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName127=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName128=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName129=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName130=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName131=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Programmable-Oscillators
LibName132=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Pushbutton-Switches
LibName133=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName134=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Reed-Relays
LibName135=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Resistor-Networks-Arrays
LibName136=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Amplifiers
LibName137=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Antennas
LibName138=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Demodulators
LibName139=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Detectors
LibName140=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName141=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Receivers
LibName142=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Switches
LibName143=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-ICs
LibName144=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transceiver-Modules
LibName145=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RF-Transmitters
LibName146=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName147=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName148=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName149=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName150=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Slide-Switches
LibName151=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Solid-State-Relays
LibName152=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Specialized-ICs
LibName153=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Specialized-Sensors
LibName154=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Surge-Suppression-ICs
LibName155=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Tactile-Switches
LibName156=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName157=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName158=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName159=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-SCRs
LibName160=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Thyristors-TRIACs
LibName161=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Toggle-Switches
LibName162=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName163=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName164=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName165=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName166=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName167=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName168=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName169=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Transistors-JFETs
LibName170=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_Trimmer-Potentiometers
LibName171=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_TVS-Diodes
LibName172=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_TVS-Mixed-Technology
LibName173=/Users/kristenkeilman/Desktop/KiCad Libraries/digikey-kicad-library-master/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName174=/Users/kristenkeilman/Desktop/KiCad Libraries/kicad-lib-master/components/_linear-regulators
LibName175=/Users/kristenkeilman/Desktop/KiCad Libraries/kicad_third_party_Libraries/SparkFun-KiCad-Libraries-master/Libraries/SparkFun-IC-Microcontroller
LibName176=/Users/kristenkeilman/Desktop/KiCad Libraries/kicad-templates-master/Arduino_Nano/Arduino_Nano-cache
LibName177=/Users/kristenkeilman/Desktop/KiCad Libraries/arduino_lib-master/arduino
LibName178=/Users/kristenkeilman/Desktop/KiCad Libraries/kicad-lib-master/components/_connectors
